# Escuela Politécnica Nacional
## Examen 2do Bimestre
### Miguel Esteban Álvarez Naranjo

In [93]:
import pandas as pd
import re

In [5]:
path_empleados_petroEC = 'C:/Users/MIGUELESTEBAN/Documents/GitHub/py-alvarez-naranjo-miguel-esteban/Examen 2do Bim/Empleados-PetroEcuador.csv'
path_empleados_distribuidores = 'C:/Users/MIGUELESTEBAN/Documents/GitHub/py-alvarez-naranjo-miguel-esteban/Examen 2do Bim/Empleados-Distribuidores.csv'

In [133]:
df_petroEc = pd.read_csv(path_empleados_petroEC, sep=';')
df_petroEc

   NOMBRE Y APELLIDO       CÉDULA             CORREO ELECTRÓNICO
0        Omar Ferrer   1712159811                    @hotmail.ec
1       Marco Castro  ´0701753452     nikita.zambrano@hotmail.ec
2        Gerard Peña  ´0920655149  carolina.bohorquez@hotmail.ec
3        Darío Ramos  ´0925712952      daniel.alvarez@hotmail.ec
4        Isaac Ortiz  ´0706171635     vicky.matamoros@hotmail.ec
5       Juan Fuentes  ´0922662821          ivan.anton@hotmail.ec
6      Santiago Roig  ´0532527212     germania.flores@hotmail.ec
7        Bruno Serra   1722499583    daniel.soledispa@hotmail.ec
8     Roberto Garcia   1731291508       diegoc.guerra@hotmail.ec
9          Alex Sole   1707003383       wilson.granja@hotmail.ec
10         Pablo Mas   1712208743        fernado.diaz@hotmail.ec
11       Andrea Cano   1716063353         andrea.vera@hotmail.ec
12        Cesar Saez   ´060260573       cesar.salazar@hotmail.ec

In [134]:
df_distribuidores = pd.read_csv(path_empleados_distribuidores, sep=';')
df_distribuidores

,NOMBRE Y APELLIDO,CÉDULA,CORREO ELECTRÓNICO,EMPRESA,RUC
0,EDUARDO CÓRDOVA,1102956953,ecorrdova10@hotmail.com,IMPORTADORA LAVACOR CIA. LTDA,1191726744001
1,JUAN DIAS,1303373010,jcedenot@corporacionmarzam.com,NAVIERA MARNIZAM CIA. LTDA,139009264001
2,FAUSTO CORDOVA,´0903307692,fbayddas@tire-experts.com.ec,NATIONALTIRE EXPERTS S.A.,1790202356001
3,JAIRO PAREDES,1733220428,jmqwlina@corpetrolsa.com,SERVAMAIN S.A.,´0991380989001
4,JOSÉ LUIS SANCHEZ,´0923335352,jpa44dese@gmail.com,VENTURAMARKET S.A.,`0992942685001

### Eliminar caracter especial en cedula

In [135]:
df_cedula = pd.DataFrame(df_petroEc['CÉDULA'])
df_cedula_corregida = []

def eliminar_caracter_especial(cedula):
    cedula = str(cedula).replace('´', '')
    df_cedula_corregida.append(cedula)
    return cedula

df_cedula.applymap(eliminar_caracter_especial)
df_cedula_corregida = pd.DataFrame(df_cedula_corregida)
df_cedula_corregida.rename(columns = {0:'CÉDULA'}, inplace = True) 
df_petroEc.drop(['CÉDULA'], axis='columns', inplace=True)
df_petroEc = pd.merge(df_petroEc.copy(), df_cedula_corregida, left_index=True, right_index=True)
df_petroEc

   NOMBRE Y APELLIDO             CORREO ELECTRÓNICO      CÉDULA
0        Omar Ferrer                    @hotmail.ec  1712159811
1       Marco Castro     nikita.zambrano@hotmail.ec  0701753452
2        Gerard Peña  carolina.bohorquez@hotmail.ec  0920655149
3        Darío Ramos      daniel.alvarez@hotmail.ec  0925712952
4        Isaac Ortiz     vicky.matamoros@hotmail.ec  0706171635
5       Juan Fuentes          ivan.anton@hotmail.ec  0922662821
6      Santiago Roig     germania.flores@hotmail.ec  0532527212
7        Bruno Serra    daniel.soledispa@hotmail.ec  1722499583
8     Roberto Garcia       diegoc.guerra@hotmail.ec  1731291508
9          Alex Sole       wilson.granja@hotmail.ec  1707003383
10         Pablo Mas        fernado.diaz@hotmail.ec  1712208743
11       Andrea Cano         andrea.vera@hotmail.ec  1716063353
12        Cesar Saez       cesar.salazar@hotmail.ec   060260573

In [136]:
df_cedula_dis = pd.DataFrame(df_distribuidores['CÉDULA'])
df_cedula_corregida_dis = []

def eliminar_caracter_especial(cedula):
    cedula = str(cedula).replace('´', '')
    df_cedula_corregida_dis.append(cedula)
    return cedula

df_cedula_dis.applymap(eliminar_caracter_especial)
df_cedula_corregida_dis = pd.DataFrame(df_cedula_corregida_dis)
df_cedula_corregida_dis.rename(columns = {0:'CÉDULA'}, inplace = True) 
df_distribuidores.drop(['CÉDULA'], axis='columns', inplace=True)
df_distribuidores = pd.merge(df_distribuidores.copy(), df_cedula_corregida_dis, left_index=True, right_index=True)
df_distribuidores

,NOMBRE Y APELLIDO,CORREO ELECTRÓNICO,EMPRESA,RUC,CÉDULA
0,EDUARDO CÓRDOVA,ecorrdova10@hotmail.com,IMPORTADORA LAVACOR CIA. LTDA,1191726744001,1102956953
1,JUAN DIAS,jcedenot@corporacionmarzam.com,NAVIERA MARNIZAM CIA. LTDA,139009264001,1303373010
2,FAUSTO CORDOVA,fbayddas@tire-experts.com.ec,NATIONALTIRE EXPERTS S.A.,1790202356001,0903307692
3,JAIRO PAREDES,jmqwlina@corpetrolsa.com,SERVAMAIN S.A.,´0991380989001,1733220428
4,JOSÉ LUIS SANCHEZ,jpa44dese@gmail.com,VENTURAMARKET S.A.,`0992942685001,0923335352

### Eliminar caracter especial en ruc

In [137]:
df_ruc_dis = pd.DataFrame(df_distribuidores['RUC'])
df_ruc_corregida_dis = []

def eliminar_caracter_especial(RUC):
    RUC = str(RUC).replace('´', '')
    RUC = str(RUC).replace('`', '')
    df_ruc_corregida_dis.append(RUC)
    
    return RUC

df_ruc_dis.applymap(eliminar_caracter_especial)
df_ruc_corregida_dis = pd.DataFrame(df_ruc_corregida_dis)
df_ruc_corregida_dis.rename(columns = {0:'RUC'}, inplace = True) 
df_distribuidores.drop(['RUC'], axis='columns', inplace=True)
df_distribuidores = pd.merge(df_distribuidores.copy(), df_ruc_corregida_dis, left_index=True, right_index=True)
df_distribuidores

,NOMBRE Y APELLIDO,CORREO ELECTRÓNICO,EMPRESA,CÉDULA,RUC
0,EDUARDO CÓRDOVA,ecorrdova10@hotmail.com,IMPORTADORA LAVACOR CIA. LTDA,1102956953,1191726744001
1,JUAN DIAS,jcedenot@corporacionmarzam.com,NAVIERA MARNIZAM CIA. LTDA,1303373010,139009264001
2,FAUSTO CORDOVA,fbayddas@tire-experts.com.ec,NATIONALTIRE EXPERTS S.A.,0903307692,1790202356001
3,JAIRO PAREDES,jmqwlina@corpetrolsa.com,SERVAMAIN S.A.,1733220428,0991380989001
4,JOSÉ LUIS SANCHEZ,jpa44dese@gmail.com,VENTURAMARKET S.A.,0923335352,0992942685001

### Verificar Correo Electronico

In [138]:
df_correo_petro = pd.DataFrame(df_petroEc['CORREO ELECTRÓNICO'])
df_correo_valido = []

def validar_correo(correo):
    if not re.fullmatch(r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)", correo):
        correo = ''
        df_correo_valido.append(correo)
        return correo
    else:
        df_correo_valido.append(correo)
        return correo
df_correo_petro.applymap(validar_correo)
df_correo_valido = pd.DataFrame(df_correo_valido)
df_correo_valido.rename(columns = {0:'CORREO ELECTRÓNICO'}, inplace = True) 
df_petroEc.drop(['CORREO ELECTRÓNICO'], axis='columns', inplace=True)
df_petroEc = pd.merge(df_petroEc.copy(), df_correo_valido, left_index=True, right_index=True)
df_petroEc

   NOMBRE Y APELLIDO      CÉDULA             CORREO ELECTRÓNICO
0        Omar Ferrer  1712159811
1       Marco Castro  0701753452     nikita.zambrano@hotmail.ec
2        Gerard Peña  0920655149  carolina.bohorquez@hotmail.ec
3        Darío Ramos  0925712952      daniel.alvarez@hotmail.ec
4        Isaac Ortiz  0706171635     vicky.matamoros@hotmail.ec
5       Juan Fuentes  0922662821          ivan.anton@hotmail.ec
6      Santiago Roig  0532527212     germania.flores@hotmail.ec
7        Bruno Serra  1722499583    daniel.soledispa@hotmail.ec
8     Roberto Garcia  1731291508       diegoc.guerra@hotmail.ec
9          Alex Sole  1707003383       wilson.granja@hotmail.ec
10         Pablo Mas  1712208743        fernado.diaz@hotmail.ec
11       Andrea Cano  1716063353         andrea.vera@hotmail.ec
12        Cesar Saez   060260573       cesar.salazar@hotmail.ec

In [139]:
df_correo_dis = pd.DataFrame(df_distribuidores['CORREO ELECTRÓNICO'])
df_correo_valido_dis = []

def validar_correo(correo):
    if not re.fullmatch(r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)", correo):
        correo = ''
        df_correo_valido_dis.append(correo)
        return correo
    else:
        df_correo_valido_dis.append(correo)
        return correo
df_correo_dis.applymap(validar_correo)
df_correo_valido_dis = pd.DataFrame(df_correo_valido_dis)
df_correo_valido_dis.rename(columns = {0:'CORREO ELECTRÓNICO'}, inplace = True) 
df_distribuidores.drop(['CORREO ELECTRÓNICO'], axis='columns', inplace=True)
df_distribuidores = pd.merge(df_distribuidores.copy(), df_correo_valido_dis, left_index=True, right_index=True)
df_distribuidores

,NOMBRE Y APELLIDO,EMPRESA,CÉDULA,RUC,CORREO ELECTRÓNICO
0,EDUARDO CÓRDOVA,IMPORTADORA LAVACOR CIA. LTDA,1102956953,1191726744001,ecorrdova10@hotmail.com
1,JUAN DIAS,NAVIERA MARNIZAM CIA. LTDA,1303373010,139009264001,jcedenot@corporacionmarzam.com
2,FAUSTO CORDOVA,NATIONALTIRE EXPERTS S.A.,0903307692,1790202356001,fbayddas@tire-experts.com.ec
3,JAIRO PAREDES,SERVAMAIN S.A.,1733220428,0991380989001,jmqwlina@corpetrolsa.com
4,JOSÉ LUIS SANCHEZ,VENTURAMARKET S.A.,0923335352,0992942685001,jpa44dese@gmail.com

### Separar nombre y apellido

In [140]:
df = df_petroEc.copy()['NOMBRE Y APELLIDO'].apply(lambda nombre: pd.Series(nombre.split(' ')))
df.rename(columns = {0:'NOMBRE', 1:'APELLIDO'}, inplace = True) 
df_petroEc = pd.merge(df, df_petroEc.copy(), left_index=True, right_index=True)
df_petroEc.drop(['NOMBRE Y APELLIDO'], axis='columns', inplace=True)
df_petroEc

      NOMBRE APELLIDO      CÉDULA             CORREO ELECTRÓNICO
0       Omar   Ferrer  1712159811
1      Marco   Castro  0701753452     nikita.zambrano@hotmail.ec
2     Gerard     Peña  0920655149  carolina.bohorquez@hotmail.ec
3      Darío    Ramos  0925712952      daniel.alvarez@hotmail.ec
4      Isaac    Ortiz  0706171635     vicky.matamoros@hotmail.ec
5       Juan  Fuentes  0922662821          ivan.anton@hotmail.ec
6   Santiago     Roig  0532527212     germania.flores@hotmail.ec
7      Bruno    Serra  1722499583    daniel.soledispa@hotmail.ec
8    Roberto   Garcia  1731291508       diegoc.guerra@hotmail.ec
9       Alex     Sole  1707003383       wilson.granja@hotmail.ec
10     Pablo      Mas  1712208743        fernado.diaz@hotmail.ec
11    Andrea     Cano  1716063353         andrea.vera@hotmail.ec
12     Cesar     Saez   060260573       cesar.salazar@hotmail.ec

In [141]:
df = df_distribuidores.copy()['NOMBRE Y APELLIDO'].apply(lambda nombre: pd.Series(nombre.split(' ')))
df.rename(columns = {0:'NOMBRE', 1:'APELLIDO'}, inplace = True) 
df_distribuidores = pd.merge(df, df_distribuidores.copy(), left_index=True, right_index=True)
df_distribuidores.drop(['NOMBRE Y APELLIDO', 2], axis='columns', inplace=True)
df_distribuidores

,NOMBRE,APELLIDO,EMPRESA,CÉDULA,RUC,CORREO ELECTRÓNICO
0,EDUARDO,CÓRDOVA,IMPORTADORA LAVACOR CIA. LTDA,1102956953,1191726744001,ecorrdova10@hotmail.com
1,JUAN,DIAS,NAVIERA MARNIZAM CIA. LTDA,1303373010,139009264001,jcedenot@corporacionmarzam.com
2,FAUSTO,CORDOVA,NATIONALTIRE EXPERTS S.A.,0903307692,1790202356001,fbayddas@tire-experts.com.ec
3,JAIRO,PAREDES,SERVAMAIN S.A.,1733220428,0991380989001,jmqwlina@corpetrolsa.com
4,JOSÉ,LUIS,VENTURAMARKET S.A.,0923335352,0992942685001,jpa44dese@gmail.com

### Completar los datos de empresa y ruc

In [142]:
#1768153530001
df_empresa_petro = []
df_ruc_petro = []
for i in range(13):
    df_empresa_petro.append('PETROECUADOR')
    df_ruc_petro.append('1768153530001')

df_empresa_petro = pd.DataFrame(df_empresa_petro)
df_ruc_petro = pd.DataFrame(df_ruc_petro)
df_empresa_petro.rename(columns = {0:'EMPRESA'}, inplace = True) 
df_ruc_petro.rename(columns = {0:'RUC'}, inplace = True) 

df_empresa_ruc_petro = pd.merge(df_empresa_petro, df_ruc_petro, left_index=True, right_index=True)
df_petroEc = pd.merge(df_petroEc.copy(), df_empresa_ruc_petro, left_index=True, right_index=True)
df_petroEc

,NOMBRE,APELLIDO,CÉDULA,CORREO ELECTRÓNICO,EMPRESA,RUC
0,Omar,Ferrer,1712159811,,PETROECUADOR,1768153530001
1,Marco,Castro,0701753452,nikita.zambrano@hotmail.ec,PETROECUADOR,1768153530001
2,Gerard,Peña,0920655149,carolina.bohorquez@hotmail.ec,PETROECUADOR,1768153530001
3,Darío,Ramos,0925712952,daniel.alvarez@hotmail.ec,PETROECUADOR,1768153530001
4,Isaac,Ortiz,0706171635,vicky.matamoros@hotmail.ec,PETROECUADOR,1768153530001
5,Juan,Fuentes,0922662821,ivan.anton@hotmail.ec,PETROECUADOR,1768153530001
6,Santiago,Roig,0532527212,germania.flores@hotmail.ec,PETROECUADOR,1768153530001
7,Bruno,Serra,1722499583,daniel.soledispa@hotmail.ec,PETROECUADOR,1768153530001
8,Roberto,Garcia,1731291508,diegoc.guerra@hotmail.ec,PETROECUADOR,1768153530001
9,Alex,Sole,1707003383,wilson.granja@hotmail.ec,PETROECUADOR,1768153530001
10,Pablo,Mas,1712208743,fernado.diaz@hotmail.ec,PETROECUADOR,1768153530001
11,Andrea,Cano,1716063353,andrea.vera@hotmail.ec,PETROECUADOR,1768153530001
12,Cesar,Saez,060260573,cesar.salazar@hotmail.ec,PETROECUADOR,1768153530001

### Unir los datasets

In [147]:
cols = ['NOMBRE', 'APELLIDO', 'CÉDULA', 'CORREO ELECTRÓNICO', 'EMPRESA', 'RUC']
df_petroEc = df_petroEc[cols]
df_distribuidores = df_distribuidores[cols]
df_completo_empleados = pd.concat([df_petroEc, df_distribuidores])
df_completo_empleados

,NOMBRE,APELLIDO,CÉDULA,CORREO ELECTRÓNICO,EMPRESA,RUC
0,Omar,Ferrer,1712159811,,PETROECUADOR,1768153530001
1,Marco,Castro,0701753452,nikita.zambrano@hotmail.ec,PETROECUADOR,1768153530001
2,Gerard,Peña,0920655149,carolina.bohorquez@hotmail.ec,PETROECUADOR,1768153530001
3,Darío,Ramos,0925712952,daniel.alvarez@hotmail.ec,PETROECUADOR,1768153530001
4,Isaac,Ortiz,0706171635,vicky.matamoros@hotmail.ec,PETROECUADOR,1768153530001
5,Juan,Fuentes,0922662821,ivan.anton@hotmail.ec,PETROECUADOR,1768153530001
6,Santiago,Roig,0532527212,germania.flores@hotmail.ec,PETROECUADOR,1768153530001
7,Bruno,Serra,1722499583,daniel.soledispa@hotmail.ec,PETROECUADOR,1768153530001
8,Roberto,Garcia,1731291508,diegoc.guerra@hotmail.ec,PETROECUADOR,1768153530001
9,Alex,Sole,1707003383,wilson.granja@hotmail.ec,PETROECUADOR,1768153530001
10,Pablo,Mas,1712208743,fernado.diaz@hotmail.ec,PETROECUADOR,1768153530001
11,Andrea,Cano,1716063353,andrea.vera@hotmail.ec,PETROECUADOR,1768153530001
12,Cesar,Saez,060260573,cesar.salazar@hotmail.ec,PETROECUADOR,1768153530001
0,EDUARDO,CÓRDOVA,1102956953,ecorrdova10@hotmail.com,IMPORTADORA LAVACOR CIA. LTDA,1191726744001
1,JUAN,DIAS,1303373010,jcedenot@corporacionmarzam.com,NAVIERA MARNIZAM CIA. LTDA,139009264001
2,FAUSTO,CORDOVA,0903307692,fbayddas@tire-experts.com.ec,NATIONALTIRE EXPERTS S.A.,1790202356001
3,JAIRO,PAREDES,1733220428,jmqwlina@corpetrolsa.com,SERVAMAIN S.A.,0991380989001
4,JOSÉ,LUIS,0923335352,jpa44dese@gmail.com,VENTURAMARKET S.A.,0992942685001

### Exportar en excel el resultado final

In [149]:
df_completo_empleados.to_excel('empleados-py-final.xlsx', index = False)